#!/usr/bin/env node
// Generates src/index.ts: `export * from './ui/<name>'` for every src/ui/*.tsx. Idempotent — anyone may run it.
import { readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = path.dirname(fileURLToPath(new URL('../package.json', import.meta.url)));
const names = readdirSync(path.join(root, 'src/ui')).filter((f) => f.endsWith('.tsx')).map((f) => f.slice(0, -4)).sort();
const body = `// Generated by scripts/gen-index.mjs — do not edit by hand.\n${names.map((n) => `export * from './ui/${n}';`).join('\n')}\n`;
writeFileSync(path.join(root, 'src/index.ts'), body);
console.log(`src/index.ts → ${names.length} modules`);
