import type { BrandInput } from '@strata/theme-engine';

/**
 * FALLBACK ONLY. The site reads its brand from tenants/house/brand.json via getHouseBrand() in lib/tenants.ts,
 * the same file the registry's strata-tokens-house item is built from. This copy is used when that file is missing.
 *
 * The docs site's own brand ("House"), generated by the same engine as every tenant.
 * Monochrome on purpose: tenant colours are the only colour on the site.
 *
 * #18181b (near-black) keeps light mode crisp: black buttons, white labels, black focus ring.
 * In dark mode the engine's visibility rule lifts primary fills to #4a4a4e (2.2:1 against the canvas)
 * and the focus ring to #b7b7ba — a grey, but a findable one, and it shows the solver at work.
 * Lighter near-neutrals (#3f3f46, #52525b) avoid the lift but make light mode look washed out.
 */
export const HOUSE: BrandInput = {
  name: 'Strata',
  primary: '#18181b',
  neutral: 'neutral',
  shape: 'soft',
  typePair: 'precise',
  density: 'comfortable',
};

/** data-strata-theme id for the house theme inside previews. */
export const HOUSE_ID = 'house';

