import type { Metadata } from 'next';
import { ThemeScope, ToastRegion } from '@strata/react';
import { getColorTenants } from '@/components/colors/color-data';
import { ColorsView } from '@/components/colors/colors-view';
import { PageShell } from '@/components/page/page-shell';

export const metadata: Metadata = {
  title: 'Colors',
  description: 'Every tenant’s 12-step OKLCH ramps in light and dark, generated by the Strata theme engine.',
};

export default function Colors() {
  const tenants = getColorTenants();
  const scheme = tenants[0]?.schemes[0];
  const ramps = scheme?.ramps.length ?? 0;
  const steps = scheme?.ramps[0]?.swatches.length ?? 0;
  return (
    <PageShell
      eyebrow="Colors"
      title={
        <>
          Every ramp, <em>every brand</em>
        </>
      }
      description={`Each brand’s ${ramps} ramps of ${steps} steps, light and dark, generated by the theme engine from its brand file. Click a swatch to copy it.`}
    >
      {/* The page's own scope, so the toast region copies the house theme and the site's scheme. */}
      <ThemeScope theme="house" data-strata-scheme="site">
        <ColorsView tenants={tenants} />
        <ToastRegion placement="bottom-end" />
      </ThemeScope>
    </PageShell>
  );
}
