// GENERATED FILE. Do not edit by hand.
// Strata design tokens for Jetpack Compose. Brand: Vela.
// Generated by @strata/theme-engine@0.1.0 (toCompose). Rebuild with `pnpm tokens`.
//
// Tokens only: Strata has no native components. See README-native.md in @strata/tokens.
// - Colours are the engine's 8-bit sRGB values, unchanged (no Display P3, no re-derivation), so the
//   contrast the engine checked is the contrast the app shows. `pnpm tokens` reads the colours back
//   out of this file and re-checks every contrast pair on them.
// - 1 CSS px = 1 dp. Font sizes are sp, so they follow the user's font size setting.
// - Tokens carry no layout direction. Compose mirrors layouts from the locale.
// - Control heights are web design values and can be below the 48.dp touch target.
// - Left out on purpose (reasons in README-native.md): --strata-hairline, --strata-sheen, --strata-motion-spring.

package com.strata.tokens

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.animation.core.SpringSpec
import androidx.compose.animation.core.spring
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp
import kotlin.math.sqrt

/**
 * One layer of a layered shadow, in dp, as written for the web. Compose has no layered or spread
 * shadow; draw the layers yourself or map them to an elevation.
 */
@Immutable
data class StrataShadowLayer(
    val color: Color,
    val offsetX: Dp,
    val offsetY: Dp,
    val blur: Dp,
    val spread: Dp,
    val inset: Boolean,
)

/**
 * Semantic colour roles and the chart palette for one colour scheme. Exact 8-bit sRGB values from
 * the engine. `pnpm tokens` re-checks every contrast pair on the values as written.
 */
@Immutable
data class StrataColors(
    /** `--strata-color-surface-canvas` */
    val surfaceCanvas: Color,
    /** `--strata-color-surface-default` */
    val surfaceDefault: Color,
    /** `--strata-color-surface-raised` */
    val surfaceRaised: Color,
    /** `--strata-color-surface-sunken` */
    val surfaceSunken: Color,
    /** `--strata-color-surface-selected` */
    val surfaceSelected: Color,
    /** `--strata-color-surface-inverse` */
    val surfaceInverse: Color,
    /** `--strata-color-text-default` */
    val textDefault: Color,
    /** `--strata-color-text-subtle` */
    val textSubtle: Color,
    /** `--strata-color-text-disabled` */
    val textDisabled: Color,
    /** `--strata-color-text-inverse` */
    val textInverse: Color,
    /** `--strata-color-text-brand` */
    val textBrand: Color,
    /** `--strata-color-border-subtle` */
    val borderSubtle: Color,
    /** `--strata-color-border-default` */
    val borderDefault: Color,
    /** `--strata-color-border-strong` */
    val borderStrong: Color,
    /** `--strata-color-action-primary-bg` */
    val actionPrimaryBg: Color,
    /** `--strata-color-action-primary-fg` */
    val actionPrimaryFg: Color,
    /** `--strata-color-action-primary-hover` */
    val actionPrimaryHover: Color,
    /** `--strata-color-action-primary-pressed` */
    val actionPrimaryPressed: Color,
    /** `--strata-color-action-primary-border` */
    val actionPrimaryBorder: Color,
    /** `--strata-color-action-secondary-bg` */
    val actionSecondaryBg: Color,
    /** `--strata-color-action-secondary-fg` */
    val actionSecondaryFg: Color,
    /** `--strata-color-action-secondary-hover` */
    val actionSecondaryHover: Color,
    /** `--strata-color-action-secondary-pressed` */
    val actionSecondaryPressed: Color,
    /** `--strata-color-accent-bg` */
    val accentBg: Color,
    /** `--strata-color-accent-fg` */
    val accentFg: Color,
    /** `--strata-color-accent-subtle` */
    val accentSubtle: Color,
    /** `--strata-color-accent-text` */
    val accentText: Color,
    /** `--strata-color-focus-ring` */
    val focusRing: Color,
    /** `--strata-color-feedback-success-bg` */
    val feedbackSuccessBg: Color,
    /** `--strata-color-feedback-success-fg` */
    val feedbackSuccessFg: Color,
    /** `--strata-color-feedback-success-border` */
    val feedbackSuccessBorder: Color,
    /** `--strata-color-feedback-success-solid` */
    val feedbackSuccessSolid: Color,
    /** `--strata-color-feedback-success-on-solid` */
    val feedbackSuccessOnSolid: Color,
    /** `--strata-color-feedback-warning-bg` */
    val feedbackWarningBg: Color,
    /** `--strata-color-feedback-warning-fg` */
    val feedbackWarningFg: Color,
    /** `--strata-color-feedback-warning-border` */
    val feedbackWarningBorder: Color,
    /** `--strata-color-feedback-warning-solid` */
    val feedbackWarningSolid: Color,
    /** `--strata-color-feedback-warning-on-solid` */
    val feedbackWarningOnSolid: Color,
    /** `--strata-color-feedback-danger-bg` */
    val feedbackDangerBg: Color,
    /** `--strata-color-feedback-danger-fg` */
    val feedbackDangerFg: Color,
    /** `--strata-color-feedback-danger-border` */
    val feedbackDangerBorder: Color,
    /** `--strata-color-feedback-danger-solid` */
    val feedbackDangerSolid: Color,
    /** `--strata-color-feedback-danger-on-solid` */
    val feedbackDangerOnSolid: Color,
    /** `--strata-color-feedback-info-bg` */
    val feedbackInfoBg: Color,
    /** `--strata-color-feedback-info-fg` */
    val feedbackInfoFg: Color,
    /** `--strata-color-feedback-info-border` */
    val feedbackInfoBorder: Color,
    /** `--strata-color-feedback-info-solid` */
    val feedbackInfoSolid: Color,
    /** `--strata-color-feedback-info-on-solid` */
    val feedbackInfoOnSolid: Color,
    /** `--strata-chart-1` */
    val chart1: Color,
    /** `--strata-chart-2` */
    val chart2: Color,
    /** `--strata-chart-3` */
    val chart3: Color,
    /** `--strata-chart-4` */
    val chart4: Color,
    /** `--strata-chart-grid` */
    val chartGrid: Color,
    /** `--strata-chart-axis` */
    val chartAxis: Color,
)

/**
 * Elevation and glass for one colour scheme. Shadows are data (layers, as on the web):
 * Modifier.shadow() takes an elevation, not layers, so draw them yourself or pick an elevation
 * that matches. Glass: glassBg is surface.raised at glassOpacity, which keeps body and secondary
 * text at 4.5:1 over a black or white backdrop.
 */
@Immutable
data class StrataEffects(
    /** `--strata-shadow-raised` */
    val shadowRaised: List<StrataShadowLayer>,
    /** `--strata-shadow-overlay` */
    val shadowOverlay: List<StrataShadowLayer>,
    /** `--strata-shadow-highlight` */
    val shadowHighlight: List<StrataShadowLayer>,
    /** `--strata-rim` */
    val rim: Color,
    /** `--strata-glow` */
    val glow: List<StrataShadowLayer>,
    /** `--strata-glass-opacity` */
    val glassOpacity: Float,
    /** `--strata-glass-bg` */
    val glassBg: Color,
    /** `--strata-glass-blur` */
    val glassBlur: Dp,
)

/** Space scale, 4-point grid. Keys are multipliers: x4 = 4 × 4 = 16 dp. */
@Immutable
data class StrataSpace(
    /** `--strata-space-0` */
    val x0: Dp,
    /** `--strata-space-1` */
    val x1: Dp,
    /** `--strata-space-2` */
    val x2: Dp,
    /** `--strata-space-3` */
    val x3: Dp,
    /** `--strata-space-4` */
    val x4: Dp,
    /** `--strata-space-5` */
    val x5: Dp,
    /** `--strata-space-6` */
    val x6: Dp,
    /** `--strata-space-8` */
    val x8: Dp,
    /** `--strata-space-10` */
    val x10: Dp,
    /** `--strata-space-12` */
    val x12: Dp,
    /** `--strata-space-16` */
    val x16: Dp,
)

/** Corner radii. Follows the brand's shape input. 9999 means "fully round". */
@Immutable
data class StrataRadius(
    /** `--strata-radius-button` */
    val button: Dp,
    /** `--strata-radius-field` */
    val field: Dp,
    /** `--strata-radius-container` */
    val container: Dp,
    /** `--strata-radius-badge` */
    val badge: Dp,
    /** `--strata-radius-pill` */
    val pill: Dp,
)

/**
 * Font family names in fallback order. The app must bundle these fonts and follow their licences;
 * web fallbacks are left out because the system font is the native fallback. An empty list means
 * the system font.
 */
@Immutable
data class StrataFontFamilies(
    /** `--strata-font-heading` */
    val heading: List<String>,
    /** `--strata-font-body` */
    val body: List<String>,
    /** `--strata-font-mono` */
    val mono: List<String>,
)

/** Type scale in sp, so sizes follow the user's font size setting. */
@Immutable
data class StrataFontSizes(
    /** `--strata-font-size-xs` */
    val xs: TextUnit,
    /** `--strata-font-size-sm` */
    val sm: TextUnit,
    /** `--strata-font-size-md` */
    val md: TextUnit,
    /** `--strata-font-size-lg` */
    val lg: TextUnit,
    /** `--strata-font-size-xl` */
    val xl: TextUnit,
    /** `--strata-font-size-2xl` */
    val xl2: TextUnit,
    /** `--strata-font-size-3xl` */
    val xl3: TextUnit,
    /** `--strata-font-size-4xl` */
    val xl4: TextUnit,
    /** `--strata-font-size-5xl` */
    val xl5: TextUnit,
)

/** Font weights. The bundled font must include each weight (or be a variable font). */
@Immutable
data class StrataFontWeights(
    /** `--strata-font-weight-regular` */
    val regular: FontWeight,
    /** `--strata-font-weight-medium` */
    val medium: FontWeight,
    /** `--strata-font-weight-semibold` */
    val semibold: FontWeight,
    /** `--strata-font-weight-bold` */
    val bold: FontWeight,
)

/** Line heights as a multiple of the font size (em), for TextStyle.lineHeight. */
@Immutable
data class StrataLineHeights(
    /** `--strata-line-height-tight` */
    val tight: TextUnit,
    /** `--strata-line-height-snug` */
    val snug: TextUnit,
    /** `--strata-line-height-normal` */
    val normal: TextUnit,
)

/**
 * Letter spacing in em, for TextStyle.letterSpacing. 0 where the script of the type pair must not
 * be letter-spaced (Arabic, Devanagari): spacing breaks the joins.
 */
@Immutable
data class StrataTracking(
    /** `--strata-font-heading-tracking` */
    val heading: TextUnit,
    /** `--strata-font-tracking-xs` */
    val xs: TextUnit,
    /** `--strata-font-tracking-sm` */
    val sm: TextUnit,
    /** `--strata-font-tracking-md` */
    val md: TextUnit,
    /** `--strata-font-tracking-lg` */
    val lg: TextUnit,
    /** `--strata-font-tracking-xl` */
    val xl: TextUnit,
    /** `--strata-font-tracking-2xl` */
    val xl2: TextUnit,
    /** `--strata-font-tracking-3xl` */
    val xl3: TextUnit,
    /** `--strata-font-tracking-4xl` */
    val xl4: TextUnit,
    /** `--strata-font-tracking-5xl` */
    val xl5: TextUnit,
    /** `--strata-font-tracking-caps` */
    val caps: TextUnit,
)

/** Durations in milliseconds (tween(durationMillis = …)) and easing curves. */
@Immutable
data class StrataMotion(
    /** `--strata-motion-duration-fast` */
    val durationFast: Int,
    /** `--strata-motion-duration-normal` */
    val durationNormal: Int,
    /** `--strata-motion-duration-slow` */
    val durationSlow: Int,
    /** `--strata-motion-duration-spring` */
    val durationSpring: Int,
    /** `--strata-motion-easing` */
    val easing: CubicBezierEasing,
    /** `--strata-motion-easing-out` */
    val easingOut: CubicBezierEasing,
)

/** The damped spring the web samples into linear(), as physics: mass, stiffness, damping. */
@Immutable
data class StrataSpring(
    /** Mass. The engine simulates its spring with mass 1. */
    val mass: Float,
    /** Stiffness. */
    val stiffness: Float,
    /** Damping coefficient (not a ratio). */
    val damping: Float,
) {
    /** damping / (2 × √(stiffness × mass)), the ratio Compose's spring() takes. */
    val dampingRatio: Float get() = damping / (2f * sqrt(stiffness * mass))

    /** A Compose spring with the same motion. Compose springs have unit mass, so stiffness is divided by [mass]. */
    fun <T> spec(): SpringSpec<T> = spring(dampingRatio = dampingRatio, stiffness = stiffness / mass)
}

/** Icon stroke width, unitless, in the icon's own 24 × 24 drawing units. */
@Immutable
data class StrataIcon(
    /** `--strata-icon-stroke` */
    val stroke: Float,
)

/**
 * Sizes that change with density. These are the web design values and are not raised for touch: a
 * control height can be below the platform minimum touch target (48.dp). Native controls must
 * still meet it, e.g. Modifier.sizeIn(minHeight = 48.dp) around a control drawn at controlHeight.
 */
@Immutable
data class StrataDensityTokens(
    /** `--strata-control-height` */
    val controlHeight: Dp,
    /** `--strata-control-padding-inline` */
    val controlPaddingInline: Dp,
    /** `--strata-table-row-height` */
    val tableRowHeight: Dp,
    /** `--strata-card-inset` */
    val cardInset: Dp,
    /** `--strata-section-gap` */
    val sectionGap: Dp,
    /** `--strata-field-gap` */
    val fieldGap: Dp,
)

/** Density modes. The brand's default is StrataTokens.DefaultDensity. */
enum class StrataDensity { Comfortable, Compact }

/** Every token value. StrataTheme reads these; use them directly outside composition. */
object StrataTokens {
    /** The brand these values came from. Data only: code should not branch on it. */
    const val BrandName: String = "Vela"

    val DefaultDensity: StrataDensity = StrataDensity.Compact

    val LightColors: StrataColors = StrataColors(
        surfaceCanvas = Color(0xFFF5F8FD),
        surfaceDefault = Color(0xFFFCFDFF),
        surfaceRaised = Color(0xFFFCFDFF),
        surfaceSunken = Color(0xFFECF0F6),
        surfaceSelected = Color(0xFFE9EEFF),
        surfaceInverse = Color(0xFF1B2025),
        textDefault = Color(0xFF1B2025),
        textSubtle = Color(0xFF565B62),
        textDisabled = Color(0xFFACB2B9),
        textInverse = Color(0xFFFCFDFF),
        textBrand = Color(0xFF3F4BCA),
        borderSubtle = Color(0xFFDBE0E6),
        borderDefault = Color(0xFFC4C9D0),
        borderStrong = Color(0xFF81878D),
        actionPrimaryBg = Color(0xFF3D45D6),
        actionPrimaryFg = Color(0xFFFFFFFF),
        actionPrimaryHover = Color(0xFF3437C8),
        actionPrimaryPressed = Color(0xFF2D27BA),
        actionPrimaryBorder = Color(0xFF3D45D6),
        actionSecondaryBg = Color(0xFFE9EEFF),
        actionSecondaryFg = Color(0xFF1C216D),
        actionSecondaryHover = Color(0xFFDCE4FF),
        actionSecondaryPressed = Color(0xFFCCD8FF),
        accentBg = Color(0xFF12B5A6),
        accentFg = Color(0xFF1B2025),
        accentSubtle = Color(0xFFD5F7F1),
        accentText = Color(0xFF007A6F),
        focusRing = Color(0xFF3D45D6),
        feedbackSuccessBg = Color(0xFFDCF7E0),
        feedbackSuccessFg = Color(0xFF0F7034),
        feedbackSuccessBorder = Color(0xFF8BCD98),
        feedbackSuccessSolid = Color(0xFF11813C),
        feedbackSuccessOnSolid = Color(0xFFFFFFFF),
        feedbackWarningBg = Color(0xFFFFEBD1),
        feedbackWarningFg = Color(0xFF7E5400),
        feedbackWarningBorder = Color(0xFFE6B061),
        feedbackWarningSolid = Color(0xFFEFA30F),
        feedbackWarningOnSolid = Color(0xFF1B2025),
        feedbackDangerBg = Color(0xFFFFE9E6),
        feedbackDangerFg = Color(0xFFAC1A1C),
        feedbackDangerBorder = Color(0xFFFF9B90),
        feedbackDangerSolid = Color(0xFFD73431),
        feedbackDangerOnSolid = Color(0xFFFFFFFF),
        feedbackInfoBg = Color(0xFFE3F0FF),
        feedbackInfoFg = Color(0xFF025FA6),
        feedbackInfoBorder = Color(0xFF84C0FE),
        feedbackInfoSolid = Color(0xFF0F74C5),
        feedbackInfoOnSolid = Color(0xFFFFFFFF),
        chart1 = Color(0xFF3D45D6),
        chart2 = Color(0xFFCE5604),
        chart3 = Color(0xFF009582),
        chart4 = Color(0xFFD765B5),
        chartGrid = Color(0xFFDBE0E6), // colors.borderSubtle
        chartAxis = Color(0xFF565B62), // colors.textSubtle
    )

    val DarkColors: StrataColors = StrataColors(
        surfaceCanvas = Color(0xFF0C0D10),
        surfaceDefault = Color(0xFF121417),
        surfaceRaised = Color(0xFF191C20),
        surfaceSunken = Color(0xFF0C0D10),
        surfaceSelected = Color(0xFF1D254C),
        surfaceInverse = Color(0xFFE9EFF7),
        textDefault = Color(0xFFE9EFF7),
        textSubtle = Color(0xFFB2B8BF),
        textDisabled = Color(0xFF4E5359),
        textInverse = Color(0xFF0C0D10),
        textBrand = Color(0xFF9FB3FF),
        borderSubtle = Color(0xFF202327),
        borderDefault = Color(0xFF2F3338),
        borderStrong = Color(0xFF7B8187),
        actionPrimaryBg = Color(0xFF3D45D6),
        actionPrimaryFg = Color(0xFFFFFFFF),
        actionPrimaryHover = Color(0xFF3437C8),
        actionPrimaryPressed = Color(0xFF2D27BA),
        actionPrimaryBorder = Color(0xFF3D45D6),
        actionSecondaryBg = Color(0xFF181E3A),
        actionSecondaryFg = Color(0xFF9FB3FF),
        actionSecondaryHover = Color(0xFF1D254C),
        actionSecondaryPressed = Color(0xFF232C5D),
        accentBg = Color(0xFF12B5A6),
        accentFg = Color(0xFF0C0D10),
        accentSubtle = Color(0xFF0D2F2B),
        accentText = Color(0xFF73D0C3),
        focusRing = Color(0xFF9FB3FF),
        feedbackSuccessBg = Color(0xFF142517),
        feedbackSuccessFg = Color(0xFF85CB93),
        feedbackSuccessBorder = Color(0xFF255632),
        feedbackSuccessSolid = Color(0xFF11813C),
        feedbackSuccessOnSolid = Color(0xFFFFFFFF),
        feedbackWarningBg = Color(0xFF2C1D08),
        feedbackWarningFg = Color(0xFFFFCA80),
        feedbackWarningBorder = Color(0xFF654200),
        feedbackWarningSolid = Color(0xFFEFA30F),
        feedbackWarningOnSolid = Color(0xFF0C0D10),
        feedbackDangerBg = Color(0xFF351613),
        feedbackDangerFg = Color(0xFFFF968A),
        feedbackDangerBorder = Color(0xFF7D2B26),
        feedbackDangerSolid = Color(0xFFD73431),
        feedbackDangerOnSolid = Color(0xFFFFFFFF),
        feedbackInfoBg = Color(0xFF122232),
        feedbackInfoFg = Color(0xFF7EBDFD),
        feedbackInfoBorder = Color(0xFF204D78),
        feedbackInfoSolid = Color(0xFF0F74C5),
        feedbackInfoOnSolid = Color(0xFFFFFFFF),
        chart1 = Color(0xFF4956E7),
        chart2 = Color(0xFFDC621E),
        chart3 = Color(0xFF00A28E),
        chart4 = Color(0xFFB14393),
        chartGrid = Color(0xFF202327), // colors.borderSubtle
        chartAxis = Color(0xFFB2B8BF), // colors.textSubtle
    )

    val LightEffects: StrataEffects = StrataEffects(
        shadowRaised = listOf(
            StrataShadowLayer(color = Color(0xFF101828).copy(alpha = 0.06f), offsetX = 0.dp, offsetY = 0.5.dp, blur = 1.dp, spread = 0.dp, inset = false),
            StrataShadowLayer(color = Color(0xFF101828).copy(alpha = 0.07f), offsetX = 0.dp, offsetY = 2.dp, blur = 8.dp, spread = (-2).dp, inset = false),
        ),
        shadowOverlay = listOf(
            StrataShadowLayer(color = Color(0xFF101828).copy(alpha = 0.06f), offsetX = 0.dp, offsetY = 0.dp, blur = 0.dp, spread = 0.5.dp, inset = false),
            StrataShadowLayer(color = Color(0xFF101828).copy(alpha = 0.12f), offsetX = 0.dp, offsetY = 8.dp, blur = 24.dp, spread = (-6).dp, inset = false),
            StrataShadowLayer(color = Color(0xFF101828).copy(alpha = 0.18f), offsetX = 0.dp, offsetY = 24.dp, blur = 64.dp, spread = (-16).dp, inset = false),
        ),
        shadowHighlight = listOf(
            StrataShadowLayer(color = Color(0xFFFFFFFF).copy(alpha = 0.2f), offsetX = 0.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, inset = true),
        ),
        rim = Color(0xFF1B2025).copy(alpha = 0.1f), // colors.textDefault at 10%
        glow = listOf(
            StrataShadowLayer(color = Color(0xFF3D45D6).copy(alpha = 0.22f), offsetX = 0.dp, offsetY = 0.dp, blur = 0.dp, spread = 1.dp, inset = false),
            StrataShadowLayer(color = Color(0xFF3D45D6).copy(alpha = 0.35f), offsetX = 0.dp, offsetY = 12.dp, blur = 40.dp, spread = (-12).dp, inset = false),
        ),
        glassOpacity = 0.83f,
        glassBg = Color(0xFFFCFDFF).copy(alpha = 0.83f), // colors.surfaceRaised at 83%
        glassBlur = 20.dp,
    )

    val DarkEffects: StrataEffects = StrataEffects(
        shadowRaised = listOf(
            StrataShadowLayer(color = Color(0xFFFFFFFF).copy(alpha = 0.06f), offsetX = 0.dp, offsetY = 0.dp, blur = 0.dp, spread = 0.5.dp, inset = false),
            StrataShadowLayer(color = Color(0xFF000000).copy(alpha = 0.3f), offsetX = 0.dp, offsetY = 1.dp, blur = 2.dp, spread = 0.dp, inset = false),
            StrataShadowLayer(color = Color(0xFF000000).copy(alpha = 0.4f), offsetX = 0.dp, offsetY = 4.dp, blur = 12.dp, spread = (-4).dp, inset = false),
        ),
        shadowOverlay = listOf(
            StrataShadowLayer(color = Color(0xFFFFFFFF).copy(alpha = 0.1f), offsetX = 0.dp, offsetY = 0.dp, blur = 0.dp, spread = 0.5.dp, inset = false),
            StrataShadowLayer(color = Color(0xFF000000).copy(alpha = 0.4f), offsetX = 0.dp, offsetY = 8.dp, blur = 24.dp, spread = (-6).dp, inset = false),
            StrataShadowLayer(color = Color(0xFF000000).copy(alpha = 0.6f), offsetX = 0.dp, offsetY = 32.dp, blur = 72.dp, spread = (-16).dp, inset = false),
        ),
        shadowHighlight = listOf(
            StrataShadowLayer(color = Color(0xFFFFFFFF).copy(alpha = 0.12f), offsetX = 0.dp, offsetY = 1.dp, blur = 0.dp, spread = 0.dp, inset = true),
        ),
        rim = Color(0xFFE9EFF7).copy(alpha = 0.18f), // colors.textDefault at 18%
        glow = listOf(
            StrataShadowLayer(color = Color(0xFF3D45D6).copy(alpha = 0.4f), offsetX = 0.dp, offsetY = 0.dp, blur = 0.dp, spread = 1.dp, inset = false),
            StrataShadowLayer(color = Color(0xFF3D45D6).copy(alpha = 0.6f), offsetX = 0.dp, offsetY = 12.dp, blur = 40.dp, spread = (-12).dp, inset = false),
        ),
        glassOpacity = 0.8f,
        glassBg = Color(0xFF191C20).copy(alpha = 0.8f), // colors.surfaceRaised at 80%
        glassBlur = 20.dp,
    )

    val ComfortableDensity: StrataDensityTokens = StrataDensityTokens(
        controlHeight = 40.dp,
        controlPaddingInline = 16.dp,
        tableRowHeight = 48.dp,
        cardInset = 28.dp,
        sectionGap = 28.dp,
        fieldGap = 16.dp,
    )

    val CompactDensity: StrataDensityTokens = StrataDensityTokens(
        controlHeight = 32.dp,
        controlPaddingInline = 12.dp,
        tableRowHeight = 40.dp,
        cardInset = 20.dp,
        sectionGap = 20.dp,
        fieldGap = 12.dp,
    )

    val Space: StrataSpace = StrataSpace(
        x0 = 0.dp,
        x1 = 4.dp,
        x2 = 8.dp,
        x3 = 12.dp,
        x4 = 16.dp,
        x5 = 20.dp,
        x6 = 24.dp,
        x8 = 32.dp,
        x10 = 40.dp,
        x12 = 48.dp,
        x16 = 64.dp,
    )

    val Radius: StrataRadius = StrataRadius(
        button = 8.dp,
        field = 8.dp,
        container = 12.dp,
        badge = 6.dp,
        pill = 9999.dp,
    )

    val FontFamilies: StrataFontFamilies = StrataFontFamilies(
        heading = listOf("Inter Tight", "Inter"),
        body = listOf("Inter"),
        mono = listOf("JetBrains Mono"),
    )

    val FontSizes: StrataFontSizes = StrataFontSizes(
        xs = 12.sp,
        sm = 13.sp,
        md = 14.sp,
        lg = 16.sp,
        xl = 20.sp,
        xl2 = 24.sp,
        xl3 = 32.sp,
        xl4 = 40.sp,
        xl5 = 48.sp,
    )

    val FontWeights: StrataFontWeights = StrataFontWeights(
        regular = FontWeight(400),
        medium = FontWeight(500),
        semibold = FontWeight(600),
        bold = FontWeight(700),
    )

    val LineHeights: StrataLineHeights = StrataLineHeights(
        tight = 1.2.em,
        snug = 1.35.em,
        normal = 1.5.em,
    )

    val Tracking: StrataTracking = StrataTracking(
        heading = (-0.01).em,
        xs = 0.em,
        sm = (-0.003).em,
        md = (-0.006).em,
        lg = (-0.011).em,
        xl = (-0.017).em,
        xl2 = (-0.019).em,
        xl3 = (-0.022).em,
        xl4 = (-0.022).em,
        xl5 = (-0.022).em,
        caps = 0.08.em,
    )

    val Motion: StrataMotion = StrataMotion(
        durationFast = 120,
        durationNormal = 200,
        durationSlow = 320,
        durationSpring = 402,
        easing = CubicBezierEasing(0.2f, 0f, 0f, 1f),
        easingOut = CubicBezierEasing(0.16f, 1f, 0.3f, 1f),
    )

    val Spring: StrataSpring = StrataSpring(
        mass = 1f,
        stiffness = 400f,
        damping = 28f,
    )

    val Icon: StrataIcon = StrataIcon(
        stroke = 1.5f,
    )

    fun colors(darkTheme: Boolean): StrataColors = if (darkTheme) DarkColors else LightColors

    fun effects(darkTheme: Boolean): StrataEffects = if (darkTheme) DarkEffects else LightEffects

    fun density(density: StrataDensity): StrataDensityTokens = when (density) {
        StrataDensity.Comfortable -> ComfortableDensity
        StrataDensity.Compact -> CompactDensity
    }
}

val LocalStrataColors = staticCompositionLocalOf<StrataColors> {
    error("No StrataColors provided. Wrap your content in StrataTheme { }.")
}

val LocalStrataEffects = staticCompositionLocalOf<StrataEffects> {
    error("No StrataEffects provided. Wrap your content in StrataTheme { }.")
}

val LocalStrataDensityTokens = staticCompositionLocalOf<StrataDensityTokens> {
    error("No StrataDensityTokens provided. Wrap your content in StrataTheme { }.")
}

/**
 * Provides the scheme- and density-dependent Strata tokens to [content]. Read them through StrataTheme:
 *
 * ```
 * StrataTheme {
 *     Text("Hi", color = StrataTheme.colors.textDefault, fontSize = StrataTheme.fontSize.md)
 * }
 * ```
 */
@Composable
fun StrataTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    density: StrataDensity = StrataTokens.DefaultDensity,
    content: @Composable () -> Unit,
) {
    CompositionLocalProvider(
        LocalStrataColors provides StrataTokens.colors(darkTheme),
        LocalStrataEffects provides StrataTokens.effects(darkTheme),
        LocalStrataDensityTokens provides StrataTokens.density(density),
        content = content,
    )
}

/**
 * Strata tokens for the current composition. Scheme and density values need a StrataTheme { }
 * above them.
 */
object StrataTheme {
    val colors: StrataColors
        @Composable @ReadOnlyComposable get() = LocalStrataColors.current

    val effects: StrataEffects
        @Composable @ReadOnlyComposable get() = LocalStrataEffects.current

    val density: StrataDensityTokens
        @Composable @ReadOnlyComposable get() = LocalStrataDensityTokens.current

    val space: StrataSpace get() = StrataTokens.Space
    val radius: StrataRadius get() = StrataTokens.Radius
    val fontFamily: StrataFontFamilies get() = StrataTokens.FontFamilies
    val fontSize: StrataFontSizes get() = StrataTokens.FontSizes
    val fontWeight: StrataFontWeights get() = StrataTokens.FontWeights
    val lineHeight: StrataLineHeights get() = StrataTokens.LineHeights
    val tracking: StrataTracking get() = StrataTokens.Tracking
    val motion: StrataMotion get() = StrataTokens.Motion
    val spring: StrataSpring get() = StrataTokens.Spring
    val icon: StrataIcon get() = StrataTokens.Icon
}
