// GENERATED FILE. Do not edit by hand.
// Strata design tokens for SwiftUI. Brand: Vela.
// Generated by @strata/theme-engine@0.1.0 (toSwiftUI). Rebuild with `pnpm tokens`.
//
// Tokens only: Strata has no native components. See README-native.md in @strata/tokens.
// - Colours are the engine's 8-bit sRGB values, unchanged (no Display P3, no re-derivation), so the
//   contrast the engine checked is the contrast the app shows. `pnpm tokens` reads the colours back
//   out of this file and re-checks every contrast pair on them.
// - Light and dark come from the environment's colorScheme: apply .strataTheme() and read
//   @Environment(\.strataColors). Values are also available directly: StrataColors.light / .dark.
// - 1 CSS px = 1 pt. Use StrataTheme.font(family:size:weight:) so text follows Dynamic Type.
// - Tokens carry no layout direction. SwiftUI mirrors layouts from the locale.
// - Control heights are web design values and can be below the 44 pt touch target.
// - Left out on purpose (reasons in README-native.md): --strata-hairline, --strata-sheen, --strata-motion-spring.

// swiftlint:disable all

import SwiftUI

/// An sRGB colour from 8-bit channels written as 0xRRGGBB: the exact bytes the engine produced.
private func srgb(_ rgb: UInt32, opacity: Double = 1) -> Color {
    Color(
        .sRGB,
        red: Double((rgb >> 16) & 0xFF) / 255,
        green: Double((rgb >> 8) & 0xFF) / 255,
        blue: Double(rgb & 0xFF) / 255,
        opacity: opacity
    )
}

/// One layer of a layered shadow, in points, as written for the web. `blur` is the CSS blur length;
/// SwiftUI .shadow(radius:) is a different measure, so check the result by eye. SwiftUI has no
/// spread or inset shadow.
public struct StrataShadowLayer: Equatable, Sendable {
    public let color: Color
    public let offsetX: CGFloat
    public let offsetY: CGFloat
    public let blur: CGFloat
    public let spread: CGFloat
    public let inset: Bool
}

/// A CSS cubic-bezier() easing curve.
public struct StrataCubicBezier: Equatable, Sendable {
    public let x1: Double
    public let y1: Double
    public let x2: Double
    public let y2: Double

    /// This curve as a SwiftUI animation.
    public func animation(duration: TimeInterval) -> Animation {
        .timingCurve(x1, y1, x2, y2, duration: duration)
    }
}

/// Semantic colour roles and the chart palette for one colour scheme. Exact 8-bit sRGB values from
/// the engine. `pnpm tokens` re-checks every contrast pair on the values as written.
public struct StrataColors: Equatable, Sendable {
    /// `--strata-color-surface-canvas`
    public let surfaceCanvas: Color
    /// `--strata-color-surface-default`
    public let surfaceDefault: Color
    /// `--strata-color-surface-raised`
    public let surfaceRaised: Color
    /// `--strata-color-surface-sunken`
    public let surfaceSunken: Color
    /// `--strata-color-surface-selected`
    public let surfaceSelected: Color
    /// `--strata-color-surface-inverse`
    public let surfaceInverse: Color
    /// `--strata-color-text-default`
    public let textDefault: Color
    /// `--strata-color-text-subtle`
    public let textSubtle: Color
    /// `--strata-color-text-disabled`
    public let textDisabled: Color
    /// `--strata-color-text-inverse`
    public let textInverse: Color
    /// `--strata-color-text-brand`
    public let textBrand: Color
    /// `--strata-color-border-subtle`
    public let borderSubtle: Color
    /// `--strata-color-border-default`
    public let borderDefault: Color
    /// `--strata-color-border-strong`
    public let borderStrong: Color
    /// `--strata-color-action-primary-bg`
    public let actionPrimaryBg: Color
    /// `--strata-color-action-primary-fg`
    public let actionPrimaryFg: Color
    /// `--strata-color-action-primary-hover`
    public let actionPrimaryHover: Color
    /// `--strata-color-action-primary-pressed`
    public let actionPrimaryPressed: Color
    /// `--strata-color-action-primary-border`
    public let actionPrimaryBorder: Color
    /// `--strata-color-action-secondary-bg`
    public let actionSecondaryBg: Color
    /// `--strata-color-action-secondary-fg`
    public let actionSecondaryFg: Color
    /// `--strata-color-action-secondary-hover`
    public let actionSecondaryHover: Color
    /// `--strata-color-action-secondary-pressed`
    public let actionSecondaryPressed: Color
    /// `--strata-color-accent-bg`
    public let accentBg: Color
    /// `--strata-color-accent-fg`
    public let accentFg: Color
    /// `--strata-color-accent-subtle`
    public let accentSubtle: Color
    /// `--strata-color-accent-text`
    public let accentText: Color
    /// `--strata-color-focus-ring`
    public let focusRing: Color
    /// `--strata-color-feedback-success-bg`
    public let feedbackSuccessBg: Color
    /// `--strata-color-feedback-success-fg`
    public let feedbackSuccessFg: Color
    /// `--strata-color-feedback-success-border`
    public let feedbackSuccessBorder: Color
    /// `--strata-color-feedback-success-solid`
    public let feedbackSuccessSolid: Color
    /// `--strata-color-feedback-success-on-solid`
    public let feedbackSuccessOnSolid: Color
    /// `--strata-color-feedback-warning-bg`
    public let feedbackWarningBg: Color
    /// `--strata-color-feedback-warning-fg`
    public let feedbackWarningFg: Color
    /// `--strata-color-feedback-warning-border`
    public let feedbackWarningBorder: Color
    /// `--strata-color-feedback-warning-solid`
    public let feedbackWarningSolid: Color
    /// `--strata-color-feedback-warning-on-solid`
    public let feedbackWarningOnSolid: Color
    /// `--strata-color-feedback-danger-bg`
    public let feedbackDangerBg: Color
    /// `--strata-color-feedback-danger-fg`
    public let feedbackDangerFg: Color
    /// `--strata-color-feedback-danger-border`
    public let feedbackDangerBorder: Color
    /// `--strata-color-feedback-danger-solid`
    public let feedbackDangerSolid: Color
    /// `--strata-color-feedback-danger-on-solid`
    public let feedbackDangerOnSolid: Color
    /// `--strata-color-feedback-info-bg`
    public let feedbackInfoBg: Color
    /// `--strata-color-feedback-info-fg`
    public let feedbackInfoFg: Color
    /// `--strata-color-feedback-info-border`
    public let feedbackInfoBorder: Color
    /// `--strata-color-feedback-info-solid`
    public let feedbackInfoSolid: Color
    /// `--strata-color-feedback-info-on-solid`
    public let feedbackInfoOnSolid: Color
    /// `--strata-chart-1`
    public let chart1: Color
    /// `--strata-chart-2`
    public let chart2: Color
    /// `--strata-chart-3`
    public let chart3: Color
    /// `--strata-chart-4`
    public let chart4: Color
    /// `--strata-chart-grid`
    public let chartGrid: Color
    /// `--strata-chart-axis`
    public let chartAxis: Color
}

/// Elevation and glass for one colour scheme. Shadows are data (layers, as on the web): stack one
/// .shadow() per layer; SwiftUI has no spread or inset, so those layers need custom drawing. Glass:
/// glassBg is surface.raised at glassOpacity, which keeps body and secondary text at 4.5:1 over a
/// black or white backdrop.
public struct StrataEffects: Equatable, Sendable {
    /// `--strata-shadow-raised`
    public let shadowRaised: [StrataShadowLayer]
    /// `--strata-shadow-overlay`
    public let shadowOverlay: [StrataShadowLayer]
    /// `--strata-shadow-highlight`
    public let shadowHighlight: [StrataShadowLayer]
    /// `--strata-rim`
    public let rim: Color
    /// `--strata-glow`
    public let glow: [StrataShadowLayer]
    /// `--strata-glass-opacity`
    public let glassOpacity: Double
    /// `--strata-glass-bg`
    public let glassBg: Color
    /// `--strata-glass-blur` (points)
    public let glassBlur: CGFloat
}

/// Space scale, 4-point grid. Keys are multipliers: x4 = 4 × 4 = 16 pt.
public struct StrataSpace: Equatable, Sendable {
    /// `--strata-space-0` (points)
    public let x0: CGFloat
    /// `--strata-space-1` (points)
    public let x1: CGFloat
    /// `--strata-space-2` (points)
    public let x2: CGFloat
    /// `--strata-space-3` (points)
    public let x3: CGFloat
    /// `--strata-space-4` (points)
    public let x4: CGFloat
    /// `--strata-space-5` (points)
    public let x5: CGFloat
    /// `--strata-space-6` (points)
    public let x6: CGFloat
    /// `--strata-space-8` (points)
    public let x8: CGFloat
    /// `--strata-space-10` (points)
    public let x10: CGFloat
    /// `--strata-space-12` (points)
    public let x12: CGFloat
    /// `--strata-space-16` (points)
    public let x16: CGFloat
}

/// Corner radii. Follows the brand's shape input. 9999 means "fully round".
public struct StrataRadius: Equatable, Sendable {
    /// `--strata-radius-button` (points)
    public let button: CGFloat
    /// `--strata-radius-field` (points)
    public let field: CGFloat
    /// `--strata-radius-container` (points)
    public let container: CGFloat
    /// `--strata-radius-badge` (points)
    public let badge: CGFloat
    /// `--strata-radius-pill` (points)
    public let pill: CGFloat
}

/// Font family names in fallback order. The app must bundle these fonts and follow their licences;
/// web fallbacks are left out because the system font is the native fallback. An empty list means
/// the system font.
public struct StrataFontFamilies: Equatable, Sendable {
    /// `--strata-font-heading`
    public let heading: [String]
    /// `--strata-font-body`
    public let body: [String]
    /// `--strata-font-mono`
    public let mono: [String]
}

/// Type scale in points at the default text size. Use StrataTheme.font(family:size:weight:) so
/// sizes follow Dynamic Type.
public struct StrataFontSizes: Equatable, Sendable {
    /// `--strata-font-size-xs` (points at the default text size)
    public let xs: CGFloat
    /// `--strata-font-size-sm` (points at the default text size)
    public let sm: CGFloat
    /// `--strata-font-size-md` (points at the default text size)
    public let md: CGFloat
    /// `--strata-font-size-lg` (points at the default text size)
    public let lg: CGFloat
    /// `--strata-font-size-xl` (points at the default text size)
    public let xl: CGFloat
    /// `--strata-font-size-2xl` (points at the default text size)
    public let xl2: CGFloat
    /// `--strata-font-size-3xl` (points at the default text size)
    public let xl3: CGFloat
    /// `--strata-font-size-4xl` (points at the default text size)
    public let xl4: CGFloat
    /// `--strata-font-size-5xl` (points at the default text size)
    public let xl5: CGFloat
}

/// Font weights. The bundled font must include each weight (or be a variable font).
public struct StrataFontWeights: Equatable, Sendable {
    /// `--strata-font-weight-regular`
    public let regular: Font.Weight
    /// `--strata-font-weight-medium`
    public let medium: Font.Weight
    /// `--strata-font-weight-semibold`
    public let semibold: Font.Weight
    /// `--strata-font-weight-bold`
    public let bold: Font.Weight
}

/// Line heights as a multiple of the font size, like CSS. Exact on iOS: NSParagraphStyle minimum
/// and maximum line height = multiple × point size. SwiftUI .lineSpacing() adds space between
/// lines, so pass (multiple × size) − the font's own line height.
public struct StrataLineHeights: Equatable, Sendable {
    /// `--strata-line-height-tight`
    public let tight: CGFloat
    /// `--strata-line-height-snug`
    public let snug: CGFloat
    /// `--strata-line-height-normal`
    public let normal: CGFloat
}

/// Letter spacing as a multiple of the font size. SwiftUI .tracking() takes points: pass value ×
/// size. 0 where the script of the type pair must not be letter-spaced (Arabic, Devanagari):
/// spacing breaks the joins.
public struct StrataTracking: Equatable, Sendable {
    /// `--strata-font-heading-tracking`
    public let heading: CGFloat
    /// `--strata-font-tracking-xs`
    public let xs: CGFloat
    /// `--strata-font-tracking-sm`
    public let sm: CGFloat
    /// `--strata-font-tracking-md`
    public let md: CGFloat
    /// `--strata-font-tracking-lg`
    public let lg: CGFloat
    /// `--strata-font-tracking-xl`
    public let xl: CGFloat
    /// `--strata-font-tracking-2xl`
    public let xl2: CGFloat
    /// `--strata-font-tracking-3xl`
    public let xl3: CGFloat
    /// `--strata-font-tracking-4xl`
    public let xl4: CGFloat
    /// `--strata-font-tracking-5xl`
    public let xl5: CGFloat
    /// `--strata-font-tracking-caps`
    public let caps: CGFloat
}

/// Durations in seconds and easing curves (StrataCubicBezier.animation(duration:)).
public struct StrataMotion: Equatable, Sendable {
    /// `--strata-motion-duration-fast` (seconds)
    public let durationFast: TimeInterval
    /// `--strata-motion-duration-normal` (seconds)
    public let durationNormal: TimeInterval
    /// `--strata-motion-duration-slow` (seconds)
    public let durationSlow: TimeInterval
    /// `--strata-motion-duration-spring` (seconds)
    public let durationSpring: TimeInterval
    /// `--strata-motion-easing`
    public let easing: StrataCubicBezier
    /// `--strata-motion-easing-out`
    public let easingOut: StrataCubicBezier
}

/// The damped spring the web samples into linear(), as physics: mass, stiffness, damping.
public struct StrataSpring: Equatable, Sendable {
    /// Mass. The engine simulates its spring with mass 1.
    public let mass: Double
    /// Stiffness.
    public let stiffness: Double
    /// Damping coefficient (not a ratio).
    public let damping: Double

    /// The same spring as a SwiftUI animation.
    public var animation: Animation {
        .interpolatingSpring(mass: mass, stiffness: stiffness, damping: damping, initialVelocity: 0)
    }
}

/// Icon stroke width, unitless, in the icon's own 24 × 24 drawing units.
public struct StrataIcon: Equatable, Sendable {
    /// `--strata-icon-stroke`
    public let stroke: Double
}

/// Sizes that change with density. These are the web design values and are not raised for touch: a
/// control height can be below the platform minimum touch target (44 pt). Native controls must
/// still meet it, e.g. .frame(minHeight: 44) with .contentShape(Rectangle()) around a control drawn
/// at controlHeight.
public struct StrataDensityTokens: Equatable, Sendable {
    /// `--strata-control-height` (points)
    public let controlHeight: CGFloat
    /// `--strata-control-padding-inline` (points)
    public let controlPaddingInline: CGFloat
    /// `--strata-table-row-height` (points)
    public let tableRowHeight: CGFloat
    /// `--strata-card-inset` (points)
    public let cardInset: CGFloat
    /// `--strata-section-gap` (points)
    public let sectionGap: CGFloat
    /// `--strata-field-gap` (points)
    public let fieldGap: CGFloat
}

/// Density modes. The brand's default is StrataTheme.defaultDensity.
public enum StrataDensity: String, CaseIterable, Sendable {
    case comfortable
    case compact
}

extension StrataColors {
    public static let light = StrataColors(
        surfaceCanvas: srgb(0xF5F8FD),
        surfaceDefault: srgb(0xFCFDFF),
        surfaceRaised: srgb(0xFCFDFF),
        surfaceSunken: srgb(0xECF0F6),
        surfaceSelected: srgb(0xE9EEFF),
        surfaceInverse: srgb(0x1B2025),
        textDefault: srgb(0x1B2025),
        textSubtle: srgb(0x565B62),
        textDisabled: srgb(0xACB2B9),
        textInverse: srgb(0xFCFDFF),
        textBrand: srgb(0x3F4BCA),
        borderSubtle: srgb(0xDBE0E6),
        borderDefault: srgb(0xC4C9D0),
        borderStrong: srgb(0x81878D),
        actionPrimaryBg: srgb(0x3D45D6),
        actionPrimaryFg: srgb(0xFFFFFF),
        actionPrimaryHover: srgb(0x3437C8),
        actionPrimaryPressed: srgb(0x2D27BA),
        actionPrimaryBorder: srgb(0x3D45D6),
        actionSecondaryBg: srgb(0xE9EEFF),
        actionSecondaryFg: srgb(0x1C216D),
        actionSecondaryHover: srgb(0xDCE4FF),
        actionSecondaryPressed: srgb(0xCCD8FF),
        accentBg: srgb(0x12B5A6),
        accentFg: srgb(0x1B2025),
        accentSubtle: srgb(0xD5F7F1),
        accentText: srgb(0x007A6F),
        focusRing: srgb(0x3D45D6),
        feedbackSuccessBg: srgb(0xDCF7E0),
        feedbackSuccessFg: srgb(0x0F7034),
        feedbackSuccessBorder: srgb(0x8BCD98),
        feedbackSuccessSolid: srgb(0x11813C),
        feedbackSuccessOnSolid: srgb(0xFFFFFF),
        feedbackWarningBg: srgb(0xFFEBD1),
        feedbackWarningFg: srgb(0x7E5400),
        feedbackWarningBorder: srgb(0xE6B061),
        feedbackWarningSolid: srgb(0xEFA30F),
        feedbackWarningOnSolid: srgb(0x1B2025),
        feedbackDangerBg: srgb(0xFFE9E6),
        feedbackDangerFg: srgb(0xAC1A1C),
        feedbackDangerBorder: srgb(0xFF9B90),
        feedbackDangerSolid: srgb(0xD73431),
        feedbackDangerOnSolid: srgb(0xFFFFFF),
        feedbackInfoBg: srgb(0xE3F0FF),
        feedbackInfoFg: srgb(0x025FA6),
        feedbackInfoBorder: srgb(0x84C0FE),
        feedbackInfoSolid: srgb(0x0F74C5),
        feedbackInfoOnSolid: srgb(0xFFFFFF),
        chart1: srgb(0x3D45D6),
        chart2: srgb(0xCE5604),
        chart3: srgb(0x009582),
        chart4: srgb(0xD765B5),
        chartGrid: srgb(0xDBE0E6), // colors.borderSubtle
        chartAxis: srgb(0x565B62) // colors.textSubtle
    )

    public static let dark = StrataColors(
        surfaceCanvas: srgb(0x0C0D10),
        surfaceDefault: srgb(0x121417),
        surfaceRaised: srgb(0x191C20),
        surfaceSunken: srgb(0x0C0D10),
        surfaceSelected: srgb(0x1D254C),
        surfaceInverse: srgb(0xE9EFF7),
        textDefault: srgb(0xE9EFF7),
        textSubtle: srgb(0xB2B8BF),
        textDisabled: srgb(0x4E5359),
        textInverse: srgb(0x0C0D10),
        textBrand: srgb(0x9FB3FF),
        borderSubtle: srgb(0x202327),
        borderDefault: srgb(0x2F3338),
        borderStrong: srgb(0x7B8187),
        actionPrimaryBg: srgb(0x3D45D6),
        actionPrimaryFg: srgb(0xFFFFFF),
        actionPrimaryHover: srgb(0x3437C8),
        actionPrimaryPressed: srgb(0x2D27BA),
        actionPrimaryBorder: srgb(0x3D45D6),
        actionSecondaryBg: srgb(0x181E3A),
        actionSecondaryFg: srgb(0x9FB3FF),
        actionSecondaryHover: srgb(0x1D254C),
        actionSecondaryPressed: srgb(0x232C5D),
        accentBg: srgb(0x12B5A6),
        accentFg: srgb(0x0C0D10),
        accentSubtle: srgb(0x0D2F2B),
        accentText: srgb(0x73D0C3),
        focusRing: srgb(0x9FB3FF),
        feedbackSuccessBg: srgb(0x142517),
        feedbackSuccessFg: srgb(0x85CB93),
        feedbackSuccessBorder: srgb(0x255632),
        feedbackSuccessSolid: srgb(0x11813C),
        feedbackSuccessOnSolid: srgb(0xFFFFFF),
        feedbackWarningBg: srgb(0x2C1D08),
        feedbackWarningFg: srgb(0xFFCA80),
        feedbackWarningBorder: srgb(0x654200),
        feedbackWarningSolid: srgb(0xEFA30F),
        feedbackWarningOnSolid: srgb(0x0C0D10),
        feedbackDangerBg: srgb(0x351613),
        feedbackDangerFg: srgb(0xFF968A),
        feedbackDangerBorder: srgb(0x7D2B26),
        feedbackDangerSolid: srgb(0xD73431),
        feedbackDangerOnSolid: srgb(0xFFFFFF),
        feedbackInfoBg: srgb(0x122232),
        feedbackInfoFg: srgb(0x7EBDFD),
        feedbackInfoBorder: srgb(0x204D78),
        feedbackInfoSolid: srgb(0x0F74C5),
        feedbackInfoOnSolid: srgb(0xFFFFFF),
        chart1: srgb(0x4956E7),
        chart2: srgb(0xDC621E),
        chart3: srgb(0x00A28E),
        chart4: srgb(0xB14393),
        chartGrid: srgb(0x202327), // colors.borderSubtle
        chartAxis: srgb(0xB2B8BF) // colors.textSubtle
    )

    /// The StrataColors for a colour scheme.
    public static func forScheme(_ scheme: ColorScheme) -> StrataColors {
        scheme == .dark ? .dark : .light
    }
}

extension StrataEffects {
    public static let light = StrataEffects(
        shadowRaised: [
            StrataShadowLayer(color: srgb(0x101828, opacity: 0.06), offsetX: 0, offsetY: 0.5, blur: 1, spread: 0, inset: false),
            StrataShadowLayer(color: srgb(0x101828, opacity: 0.07), offsetX: 0, offsetY: 2, blur: 8, spread: -2, inset: false)
        ],
        shadowOverlay: [
            StrataShadowLayer(color: srgb(0x101828, opacity: 0.06), offsetX: 0, offsetY: 0, blur: 0, spread: 0.5, inset: false),
            StrataShadowLayer(color: srgb(0x101828, opacity: 0.12), offsetX: 0, offsetY: 8, blur: 24, spread: -6, inset: false),
            StrataShadowLayer(color: srgb(0x101828, opacity: 0.18), offsetX: 0, offsetY: 24, blur: 64, spread: -16, inset: false)
        ],
        shadowHighlight: [
            StrataShadowLayer(color: srgb(0xFFFFFF, opacity: 0.2), offsetX: 0, offsetY: 1, blur: 0, spread: 0, inset: true)
        ],
        rim: srgb(0x1B2025, opacity: 0.1), // colors.textDefault at 10%
        glow: [
            StrataShadowLayer(color: srgb(0x3D45D6, opacity: 0.22), offsetX: 0, offsetY: 0, blur: 0, spread: 1, inset: false),
            StrataShadowLayer(color: srgb(0x3D45D6, opacity: 0.35), offsetX: 0, offsetY: 12, blur: 40, spread: -12, inset: false)
        ],
        glassOpacity: 0.83,
        glassBg: srgb(0xFCFDFF, opacity: 0.83), // colors.surfaceRaised at 83%
        glassBlur: 20
    )

    public static let dark = StrataEffects(
        shadowRaised: [
            StrataShadowLayer(color: srgb(0xFFFFFF, opacity: 0.06), offsetX: 0, offsetY: 0, blur: 0, spread: 0.5, inset: false),
            StrataShadowLayer(color: srgb(0x000000, opacity: 0.3), offsetX: 0, offsetY: 1, blur: 2, spread: 0, inset: false),
            StrataShadowLayer(color: srgb(0x000000, opacity: 0.4), offsetX: 0, offsetY: 4, blur: 12, spread: -4, inset: false)
        ],
        shadowOverlay: [
            StrataShadowLayer(color: srgb(0xFFFFFF, opacity: 0.1), offsetX: 0, offsetY: 0, blur: 0, spread: 0.5, inset: false),
            StrataShadowLayer(color: srgb(0x000000, opacity: 0.4), offsetX: 0, offsetY: 8, blur: 24, spread: -6, inset: false),
            StrataShadowLayer(color: srgb(0x000000, opacity: 0.6), offsetX: 0, offsetY: 32, blur: 72, spread: -16, inset: false)
        ],
        shadowHighlight: [
            StrataShadowLayer(color: srgb(0xFFFFFF, opacity: 0.12), offsetX: 0, offsetY: 1, blur: 0, spread: 0, inset: true)
        ],
        rim: srgb(0xE9EFF7, opacity: 0.18), // colors.textDefault at 18%
        glow: [
            StrataShadowLayer(color: srgb(0x3D45D6, opacity: 0.4), offsetX: 0, offsetY: 0, blur: 0, spread: 1, inset: false),
            StrataShadowLayer(color: srgb(0x3D45D6, opacity: 0.6), offsetX: 0, offsetY: 12, blur: 40, spread: -12, inset: false)
        ],
        glassOpacity: 0.8,
        glassBg: srgb(0x191C20, opacity: 0.8), // colors.surfaceRaised at 80%
        glassBlur: 20
    )

    /// The StrataEffects for a colour scheme.
    public static func forScheme(_ scheme: ColorScheme) -> StrataEffects {
        scheme == .dark ? .dark : .light
    }
}

extension StrataDensityTokens {
    public static let comfortable = StrataDensityTokens(
        controlHeight: 40,
        controlPaddingInline: 16,
        tableRowHeight: 48,
        cardInset: 28,
        sectionGap: 28,
        fieldGap: 16
    )

    public static let compact = StrataDensityTokens(
        controlHeight: 32,
        controlPaddingInline: 12,
        tableRowHeight: 40,
        cardInset: 20,
        sectionGap: 20,
        fieldGap: 12
    )

    /// The StrataDensityTokens for a density.
    public static func forDensity(_ density: StrataDensity) -> StrataDensityTokens {
        switch density {
        case .comfortable: return .comfortable
        case .compact: return .compact
        }
    }
}

/// Every value that doesn't change with scheme or density, and helpers.
public enum StrataTheme {
    /// The brand these values came from. Data only: code should not branch on it.
    public static let brandName = "Vela"
    public static let defaultDensity: StrataDensity = .compact

    public static let space = StrataSpace(
        x0: 0,
        x1: 4,
        x2: 8,
        x3: 12,
        x4: 16,
        x5: 20,
        x6: 24,
        x8: 32,
        x10: 40,
        x12: 48,
        x16: 64
    )

    public static let radius = StrataRadius(
        button: 8,
        field: 8,
        container: 12,
        badge: 6,
        pill: 9999
    )

    public static let fontFamily = StrataFontFamilies(
        heading: ["Inter Tight", "Inter"],
        body: ["Inter"],
        mono: ["JetBrains Mono"]
    )

    public static let fontSize = StrataFontSizes(
        xs: 12,
        sm: 13,
        md: 14,
        lg: 16,
        xl: 20,
        xl2: 24,
        xl3: 32,
        xl4: 40,
        xl5: 48
    )

    public static let fontWeight = StrataFontWeights(
        regular: .regular,
        medium: .medium,
        semibold: .semibold,
        bold: .bold
    )

    public static let lineHeight = StrataLineHeights(
        tight: 1.2,
        snug: 1.35,
        normal: 1.5
    )

    public static let tracking = StrataTracking(
        heading: -0.01,
        xs: 0,
        sm: -0.003,
        md: -0.006,
        lg: -0.011,
        xl: -0.017,
        xl2: -0.019,
        xl3: -0.022,
        xl4: -0.022,
        xl5: -0.022,
        caps: 0.08
    )

    public static let motion = StrataMotion(
        durationFast: 0.12,
        durationNormal: 0.2,
        durationSlow: 0.32,
        durationSpring: 0.402,
        easing: StrataCubicBezier(x1: 0.2, y1: 0, x2: 0, y2: 1),
        easingOut: StrataCubicBezier(x1: 0.16, y1: 1, x2: 0.3, y2: 1)
    )

    public static let spring = StrataSpring(
        mass: 1,
        stiffness: 400,
        damping: 28
    )

    public static let icon = StrataIcon(
        stroke: 1.5
    )

    /// A custom font at a Strata size that follows Dynamic Type. It scales relative to the Apple text
    /// style whose default size is nearest (ties go to the larger style). The app must bundle and
    /// register the font; if it isn't found, SwiftUI falls back to the system font.
    public static func font(family: String, size: CGFloat, weight: Font.Weight = .regular) -> Font {
        Font.custom(family, size: size, relativeTo: textStyle(nearest: size)).weight(weight)
    }

    /// The Apple text style whose default size (at the Large content size) is nearest to `size`.
    public static func textStyle(nearest size: CGFloat) -> Font.TextStyle {
        let styles: [(style: Font.TextStyle, size: CGFloat)] = [
            (.caption2, 11), (.caption, 12), (.footnote, 13), (.subheadline, 15), (.callout, 16),
            (.body, 17), (.title3, 20), (.title2, 22), (.title, 28), (.largeTitle, 34),
        ]
        var best = styles[0]
        for candidate in styles where abs(candidate.size - size) <= abs(best.size - size) {
            best = candidate
        }
        return best.style
    }
}

private struct StrataColorsKey: EnvironmentKey {
    static let defaultValue: StrataColors = .light
}

private struct StrataEffectsKey: EnvironmentKey {
    static let defaultValue: StrataEffects = .light
}

private struct StrataDensityTokensKey: EnvironmentKey {
    static let defaultValue: StrataDensityTokens = .forDensity(StrataTheme.defaultDensity)
}

extension EnvironmentValues {
    /// Set by .strataTheme() from the colour scheme. Light until then.
    public var strataColors: StrataColors {
        get { self[StrataColorsKey.self] }
        set { self[StrataColorsKey.self] = newValue }
    }

    /// Set by .strataTheme() from the colour scheme. Light until then.
    public var strataEffects: StrataEffects {
        get { self[StrataEffectsKey.self] }
        set { self[StrataEffectsKey.self] = newValue }
    }

    /// Set by .strataTheme(density:). The brand's default density until then.
    public var strataDensity: StrataDensityTokens {
        get { self[StrataDensityTokensKey.self] }
        set { self[StrataDensityTokensKey.self] = newValue }
    }
}

extension View {
    /// Puts Strata's colour, effect and density tokens into the environment, matching the
    /// environment's colorScheme where this modifier is applied. A subtree that sets its own
    /// colorScheme below this point needs .strataTheme() again.
    public func strataTheme(density: StrataDensity = StrataTheme.defaultDensity) -> some View {
        modifier(StrataThemeModifier(density: density))
    }
}

private struct StrataThemeModifier: ViewModifier {
    let density: StrataDensity
    @Environment(\.colorScheme) private var colorScheme

    func body(content: Content) -> some View {
        content
            .environment(\.strataColors, .forScheme(colorScheme))
            .environment(\.strataEffects, .forScheme(colorScheme))
            .environment(\.strataDensity, .forDensity(density))
    }
}
