/** The shape of schema/manifest.json. Generated by scripts/build-schemas.ts; read by the validator and renderer. */

export type Literal = string | number | boolean;

export interface ManifestProp {
  /** The React prop it maps to (usually the same name; aria-label → ariaLabel). */
  from: string;
  /**
   * enum = one of `values` · boolean · number · string · text (words, from a ReactNode prop) · numbers (number[]) ·
   * icon ({ icon }) · icon-or-false · image-url (https only).
   */
  kind: 'enum' | 'boolean' | 'number' | 'string' | 'text' | 'numbers' | 'icon' | 'icon-or-false' | 'image-url';
  values?: Literal[];
  /** Values still accepted in this major but deprecated in meta. Removed in the next major. */
  deprecatedValues?: Array<{ value: Literal; replacement: string }>;
  default?: Literal;
  required?: boolean;
  /** Set for props that aren't in meta.json, with the reason. */
  source?: string;
}

export interface ManifestNode {
  /** meta = a @syntara/react component (packages/react/meta); sdui = the schema's own node. */
  source: 'meta' | 'sdui';
  component: string | null;
  maturity: 'alpha' | 'beta' | 'stable';
  /** Only valid inside its parent (Card parts). */
  part?: boolean;
  description: string;
  props: Record<string, ManifestProp>;
  children: { kind: 'none' | 'text' | 'inline' | 'icon' | 'nodes'; required?: boolean; only?: string[] };
  slots: Record<string, { from: string; only: string[] }>;
  action?: { kinds: Array<'navigate' | 'event'>; required: boolean; from: string[] };
  rules: Array<{ id: string; message: string }>;
  /** Meta props (and example-only props) that stay on the client, with the reason. `value` = one excluded enum value. */
  excluded: Array<{ prop: string; reason: string; value?: Literal; replacement?: string }>;
}

export interface Manifest {
  $comment?: string;
  schemaVersion: string;
  nodes: Record<string, ManifestNode>;
  /** Node type → schema file, relative to schema/. */
  files: Record<string, string>;
  excludedNodes: Array<{ node: string; component: string; reason: string }>;
  excludedEverywhere: Array<{ prop: string; reason: string }>;
  outOfSlice: string;
  gapTokens: string[];
  icons: string[];
}
