// Generated by `pnpm --filter @syntara/sdui generate` (scripts/build-schemas.ts). Do not edit.
import defs from '../schema/defs.schema.json';
import node_alert from '../schema/nodes/alert.schema.json';
import node_amount from '../schema/nodes/amount.schema.json';
import node_avatar from '../schema/nodes/avatar.schema.json';
import node_badge from '../schema/nodes/badge.schema.json';
import node_button from '../schema/nodes/button.schema.json';
import node_card_action from '../schema/nodes/card-action.schema.json';
import node_card_content from '../schema/nodes/card-content.schema.json';
import node_card_description from '../schema/nodes/card-description.schema.json';
import node_card_footer from '../schema/nodes/card-footer.schema.json';
import node_card_header from '../schema/nodes/card-header.schema.json';
import node_card_title from '../schema/nodes/card-title.schema.json';
import node_card from '../schema/nodes/card.schema.json';
import node_empty_state from '../schema/nodes/empty-state.schema.json';
import node_eyebrow from '../schema/nodes/eyebrow.schema.json';
import node_heading from '../schema/nodes/heading.schema.json';
import node_icon_tile from '../schema/nodes/icon-tile.schema.json';
import node_inline from '../schema/nodes/inline.schema.json';
import node_link from '../schema/nodes/link.schema.json';
import node_meter from '../schema/nodes/meter.schema.json';
import node_progress_bar from '../schema/nodes/progress-bar.schema.json';
import node_separator from '../schema/nodes/separator.schema.json';
import node_stack from '../schema/nodes/stack.schema.json';
import node_stat_tile_group from '../schema/nodes/stat-tile-group.schema.json';
import node_stat_tile from '../schema/nodes/stat-tile.schema.json';
import node_tag from '../schema/nodes/tag.schema.json';
import node_text from '../schema/nodes/text.schema.json';
import screen from '../schema/screen.schema.json';
import manifest from '../schema/manifest.json';

/** Every schema file: shared definitions, the screen, and one per node. */
export const SCHEMAS: ReadonlyArray<Record<string, unknown>> = [defs, node_alert, node_amount, node_avatar, node_badge, node_button, node_card_action, node_card_content, node_card_description, node_card_footer, node_card_header, node_card_title, node_card, node_empty_state, node_eyebrow, node_heading, node_icon_tile, node_inline, node_link, node_meter, node_progress_bar, node_separator, node_stack, node_stat_tile_group, node_stat_tile, node_tag, node_text, screen];
export const MANIFEST_JSON: unknown = manifest;
