/**
 * Server-only: every tenant's ramps, generated by the theme engine at build time — the same call that produces
 * the site's theme CSS, so the swatches are exactly the values components render with.
 */
import {
  ROLES,
  TYPE_PAIRS,
  contrastRatio,
  generateTheme,
  hexToOklch,
  roleToCssVar,
  type BrandInput,
  type RampName,
  type Scheme,
  type Theme,
} from '@strata/theme-engine';
import { cache } from 'react';
import { getHouseBrand, getTenants } from '@/lib/tenants';
import type { BrandFact, ColorScheme, ColorTenant } from './types';

const RAMPS: ReadonlyArray<[RampName, string]> = [
  ['primary', 'Primary'],
  ['accent', 'Accent'],
  ['neutral', 'Neutral'],
  ['success', 'Success'],
  ['warning', 'Warning'],
  ['danger', 'Danger'],
  ['info', 'Info'],
];

/** When several roles share a step, the one to copy: fills and text before borders, inverse roles last. */
function rolePriority(role: string): number {
  if (role.includes('inverse')) return 3;
  if (role === 'action.primary.border') return 2;
  if (role.startsWith('border.') || role.endsWith('.border')) return 1;
  return 0;
}

/** "oklch(L C H)": L and C to 4 decimals, H to 2; H is 0 for greys. */
function oklchString(hex: string): string {
  const { l, c, h } = hexToOklch(hex);
  const n = (v: number, dp: number) => String(Number(v.toFixed(dp)));
  const cs = n(c, 4);
  return cs === '0' ? `oklch(${n(l, 4)} 0 0)` : `oklch(${n(l, 4)} ${cs} ${n(h, 2)})`;
}

function schemeData(theme: Theme, scheme: Scheme): ColorScheme {
  const s = theme.schemes[scheme];
  // Ink for hover labels: the ends of the tenant's own neutral ramp (light scheme), whichever contrasts more.
  const neutral = theme.schemes.light.ramps.neutral;
  const inks = [neutral[11] ?? '#000000', neutral[0] ?? '#ffffff'];
  const byRef = new Map<string, string[]>();
  for (const role of ROLES) {
    const ref = s.roles[role].ref;
    if (!ref) continue;
    const list = byRef.get(ref) ?? [];
    list.push(role);
    byRef.set(ref, list);
  }
  return {
    scheme,
    ramps: RAMPS.map(([name, label]) => ({
      name,
      label,
      swatches: s.ramps[name].map((hex, i) => {
        const roles = [...(byRef.get(`${name}.${i + 1}`) ?? [])].sort((a, b) => rolePriority(a) - rolePriority(b));
        const first = roles[0] as (typeof ROLES)[number] | undefined;
        const ink = inks.reduce((best, c) => (contrastRatio(c, hex) > contrastRatio(best, hex) ? c : best));
        return { step: i + 1, hex, oklch: oklchString(hex), roles, cssVar: first ? roleToCssVar(first) : undefined, ink };
      }),
    })),
  };
}

const NEUTRAL_LABEL = { cool: 'Cool', neutral: 'Neutral', warm: 'Warm', paper: 'Paper' } as const;
const SHAPE_LABEL = { sharp: 'Sharp', soft: 'Soft', round: 'Round' } as const;
const DENSITY_LABEL = { comfortable: 'Comfortable', compact: 'Compact' } as const;

function facts(brand: BrandInput, theme: Theme): BrandFact[] {
  const pair = TYPE_PAIRS[brand.typePair];
  return [
    { label: 'Primary', value: theme.input.primary, swatch: theme.input.primary },
    { label: 'Accent', value: brand.accent ? theme.input.accent : 'accent = primary', swatch: theme.input.accent },
    { label: 'Neutral', value: `${NEUTRAL_LABEL[brand.neutral].toLowerCase()} neutrals` },
    { label: 'Shape', value: SHAPE_LABEL[brand.shape].toLowerCase() },
    { label: 'Type', value: pair?.label.split('—')[1]?.trim() ?? brand.typePair },
    { label: 'Density', value: DENSITY_LABEL[brand.density].toLowerCase() },
  ];
}

const LANGUAGE = new Intl.DisplayNames('en', { type: 'language' });

/** Vela, Harbor, Qamar (brief order), then the house brand. */
export const getColorTenants = cache((): ColorTenant[] => {
  const list = getTenants().map((t) => {
    const language = LANGUAGE.of(t.locale.split('-')[0] ?? 'en') ?? t.locale;
    const product = t.product.industry && t.dir === 'ltr' ? `${t.product.industry} · ` : '';
    return {
      id: t.id,
      name: t.name,
      description: `${product}${language}, ${t.dir === 'rtl' ? 'right to left' : 'left to right'}`,
      brand: t.brand,
    };
  });
  list.push({ id: 'house', name: 'House', description: 'This site’s own brand, monochrome on purpose', brand: getHouseBrand() });
  return list.map(({ id, name, description, brand }) => {
    const theme = generateTheme(brand);
    return {
      id,
      name,
      description,
      facts: facts(brand, theme),
      schemes: [schemeData(theme, 'light'), schemeData(theme, 'dark')],
    };
  });
});
