/**
 * Theme → a standalone CSS file.
 *
 *   <sel>                                   light scheme + foundations + the tenant's default density
 *   <sel>[data-syntara-scheme="dark"]        dark colours + shadows
 *   @media (prefers-color-scheme: dark) { <sel>[data-syntara-scheme="auto"] }
 *   <sel>[data-syntara-density="compact"]    (or "comfortable" when the tenant defaults to compact)
 *
 * Mode attributes are appended to the selector (no space), so they go on the same element
 * as the theme selector: <html data-syntara-theme="vela" data-syntara-scheme="dark">.
 */
import type { Density, Theme } from '../types';
import {
  type CssVars,
  writeColorVars,
  writeDensityVars,
  writeMotionVars,
  writeRadiusVars,
  writeShadowVars,
  writeSpaceVars,
  writeTypographyVars,
} from '../css-vars';
import { ENGINE_NAME, ENGINE_VERSION, safeName, splitTopLevel } from './util';

export interface ToCSSOptions {
  /** Selector for the base block. Default ":root". Comma-separated lists are supported. */
  selector?: string;
}

type Section = readonly [comment: string, vars: CssVars];

/** Appends an attribute selector to every selector in a list: ":root, .x" → ":root[a], .x[a]". */
function withAttr(selector: string, attr: string): string {
  return splitTopLevel(selector, ',')
    .map((s) => s + attr)
    .join(', ');
}

function block(selector: string, lead: string[], sections: readonly Section[], indent = ''): string {
  const inner = indent + '  ';
  const lines: string[] = [`${indent}${selector} {`];
  for (const l of lead) lines.push(inner + l);
  for (const [comment, vars] of sections) {
    if (lines.length > 1) lines.push('');
    lines.push(`${inner}/* ${comment} */`);
    for (const name in vars) lines.push(`${inner}${name}: ${vars[name]};`);
  }
  lines.push(`${indent}}`);
  return lines.join('\n');
}

export function toCSS(theme: Theme, opts: ToCSSOptions = {}): string {
  const sel = (opts.selector ?? ':root').trim() || ':root';
  const name = safeName(theme.input.name);
  const base: Density = theme.input.density;
  const other: Density = base === 'compact' ? 'comfortable' : 'compact';

  const darkSections: Section[] = [
    ['Colour — dark', writeColorVars({}, theme, 'dark')],
    ['Elevation — dark', writeShadowVars({}, theme, 'dark')],
  ];

  const parts = [
    `/* Syntara theme: ${name} — generated by ${ENGINE_NAME} ${ENGINE_VERSION}. Do not edit by hand. */`,
    block(sel, ['color-scheme: light;'], [
      ['Space', writeSpaceVars({}, theme)],
      ['Radius', writeRadiusVars({}, theme)],
      ['Typography', writeTypographyVars({}, theme)],
      ['Motion', writeMotionVars({}, theme)],
      ['Colour — light', writeColorVars({}, theme, 'light')],
      ['Elevation — light', writeShadowVars({}, theme, 'light')],
      [`Density — ${base} (default)`, writeDensityVars({}, theme, base)],
    ]),
    block(withAttr(sel, '[data-syntara-scheme="dark"]'), ['color-scheme: dark;'], darkSections),
    [
      '@media (prefers-color-scheme: dark) {',
      block(withAttr(sel, '[data-syntara-scheme="auto"]'), ['color-scheme: dark;'], darkSections, '  '),
      '}',
    ].join('\n'),
    block(withAttr(sel, `[data-syntara-density="${other}"]`), [], [[`Density — ${other}`, writeDensityVars({}, theme, other)]]),
    // A true hairline on 2× screens: half a CSS pixel is one device pixel.
    ['@media (min-resolution: 2dppx) {', `  ${sel} { --syntara-hairline: 0.5px; }`, '}'].join('\n'),
  ];
  return parts.join('\n\n') + '\n';
}
